name: aidxpert_business
version: 1.0.0+1
publish_to: none
description: A healthcare product is the result of the interaction of capital, labour and entrepreneurship in the production process, which primarily aims to improve, maintain or prevent the deterioration of the health status of persons or reduce the consequences of ill health.

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  simple_animations: ^5.0.0
  flashy_tab_bar2: ^0.0.6
  image_picker: ^0.8.7+5
  file_picker: ^8.3.2 
  flutter_pdfview: ^1.0.2
  geolocator: ^9.0.2
  geocoding: ^2.1.0
  lottie: ^2.3.1
  flutter_onboarding_slider: ^1.0.9
  fluttertoast: ^8.2.1
  get_storage: ^2.1.1
  flutter_html: ^3.0.0-alpha.5
  photo_view: ^0.14.0
  input_quantity: ^1.2.1
  badges: ^3.1.1
  intl: ^0.18.1
  animated_toggle_switch: ^0.7.0
  flutter_typeahead: ^4.6.2
  pdf: ^3.6.0
  open_file: ^3.2.1
  custom_date_range_picker: ^1.0.10
  url_launcher: ^6.1.11
  google_maps_flutter: ^2.3.0
  flutter_polyline_points: ^1.0.0
  google_sign_in: ^6.1.4
  firebase_auth: ^4.7.0
  carousel_slider: ^5.0.0
  http: ^0.13.6
  flutter_verification_code: ^1.1.7
  permission_handler: ^11.3.1
  supabase_flutter: ^2.1.0
  connectivity_plus: ^6.1.5
  package_info_plus: ^8.0.2
  firebase_messaging: ^14.7.10
  version: ^3.0.2
  firebase_core: ^2.32.0
  webview_flutter: ^4.8.0
  google_place: ^0.4.7
  cached_network_image: ^3.3.1
  multiple_search_selection: ^2.7.2
  multi_select_flutter: ^4.1.3
  image_cropper: ^4.0.1
  path: ^1.9.0
  pull_to_refresh_flutter3: ^2.0.2
  google_maps_webservice: ^0.0.20-nullsafety.5
  timeago: ^3.7.1
  device_info_plus: ^11.3.0
  path_provider: ^2.1.5
  pdf_render: ^1.4.12
  image_gallery_saver: ^2.0.3
  syncfusion_flutter_pdfviewer: ^20.4.54
  share_plus: ^12.0.1
  qr_flutter: ^4.1.0
  get: ^4.7.2
  flutter_easyloading: ^3.0.5
  google_places_flutter: ^2.1.0
 
dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/image/
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: assets/logo/logo.png

flutter_native_splash:
  android: true
  ios: true
  web: false
  background_image: assets/logo/splash_screen.png
